version: '3'
services:
  relay-k8s-metrics-to-kr1-prd:
    hostname: relay-k8s-metrics-to-kr1-prd
    #container_name: kafka-relay
    image: jungfrau70/relay-k8s-metrics-to-kr1-prd:0.1
    # networks:
    #   netgroup:
    #     ipv4_address: 172.18.0.101
    deploy:
      resources:
        limits:
          memory: 1g
# networks:
#   netgroup:
#     name: netgroup
#     driver: bridge
#     attachable: true
#     ipam:
#       config:
#         - subnet: 172.18.0.0/16
#           gateway: 172.18.0.1