apiVersion: v1
kind: ServiceAccount
metadata:
  name: vrops-mp-user
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vrops-mp-user
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: vrops-mp-user
    namespace: kube-system
---
apiVersion: apps/v1 # apps/v1beta2 in Kube 1.8, extensions/v1beta1 in Kube < 1.8
kind: DaemonSet
metadata:
  name: vrops-telegraf-k8s
  namespace: kube-system
  labels:
    app: vrops-telegraf-k8s
  annotations:
    seccomp.security.alpha.kubernetes.io/pod: 'docker/default'
spec:
  selector:
    matchLabels:
      app: vrops-telegraf-k8s
  template:
    metadata:
      labels:
        app: vrops-telegraf-k8s
        version: v1.0
    spec:
      serviceAccountName: vrops-mp-user
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: vrops-telegraf-k8s-container
        image: telegraf:1.16.0
        resources:
          requests:
            memory: 250Mi
            cpu: 250m
          limits:
            cpu: 400m
        volumeMounts:
        - name: telegraf-d
          mountPath: /etc/telegraf
        ports:
          - name: http
            containerPort: 9273 #Port exposed
            hostPort : 31196 #Host's port - Port to expose your telegraf DaemonS Set on each node
            protocol: TCP
        env:
        - name: METRIC_SOURCE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
      automountServiceAccountToken: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: telegraf-d
        projected:
          sources:
          - configMap:
              name: vrops-telegraf-k8s-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vrops-telegraf-k8s-config
  namespace: kube-system
data:
  telegraf.conf: |
    # Configuration for telegraf agent
    [global_tags]
    region = "kr"
    az = "1"
    tenant = "prd"
    k8s_cluster_name = "coctestcluster"
    namespace = "$NAMESPACE"
    [agent]
    interval = "10s"
    round_interval = true
    metric_batch_size = 1000
    metric_buffer_limit = 10000
    collection_jitter = "0s"
    flush_interval = "10s"
    flush_jitter = "0s"
    precision = ""
    quiet = false
    hostname = "$NODE_HOSTNAME"
    omit_hostname = false
    ##################################################################
    #                            OUTPUT PLUGINS                      #
    ##################################################################
    [[outputs.kafka]]
    # URLs of kafka brokers 
    brokers = ["kafka1:9092","kafka2:9093","kafka3:9094"] # EDIT THIS LINE
    # Kafka topic for producer messages
    topic = "k8s-metrics" 
    client_id = "golangsarama__1.18.0__serverinfra__telegraf"
    routing_tag = "host"
    version = "0.11.0.2"
    compression_codec = 2
    required_acks = 1
    data_format = "influx"
    ##################################################################
    #                            INPUT PLUGINS                       #
    ##################################################################
    [[inputs.kubernetes]]
      ## URL for the kubelet
      url = "https://$NODE_IP:10250"
      insecure_skip_verify = true
    [[inputs.kube_inventory]]
      # Read metrics from the Kubernetes api
      # ## URL for the Kubernetes API
      # url = "https://rancher-uw-stg-ccs.hmc.co.kr/k8s/clusters/c-nv8c9"
      # https://10.11.79.15:6443", "https://10.11.76.160:6443", "https://10.11.79.113:6443"
      url = "https://10.11.79.113:6443"
    [[inputs.cpu]]
      ## Whether to report per-cpu stats or not
      percpu = true
      ## Whether to report total system cpu stats or not
      totalcpu = true
      ## If true, collect raw CPU time metrics.
      collect_cpu_time = false
      ## If true, compute and report the sum of all non-idle CPU states.
      report_active = false
    [[inputs.disk]]
      ## By default stats will be gathered for all mount points.
      ## Set mount_points will restrict the stats to only the specified mount points.
      # mount_points = ["/"]
      ## Ignore mount points by filesystem type.
      ignore_fs = ["tmpfs", "devtmpfs", "devfs", "overlay", "aufs", "squashfs"]
    [[inputs.diskio]]
    [[inputs.mem]]
    [[inputs.net]]
    [[inputs.processes]]
    [[inputs.swap]]
    [[inputs.system]]
    [[inputs.procstat]]
      pattern = ".*"