version: '3'
services:
  relay-to-kr1-prd-for-order-results:
    hostname: relay-to-kr1-prd-for-order-results
    container_name: relay-to-kr1-prd-for-order-results
    image: jungfrau70/relay-to-kr1-prd-for-order-results:0.1
    # networks:
    #   netgroup:
    #     ipv4_address: 172.18.0.101
    deploy:
      resources:
        limits:
          memory: 1g
# networks:
#   netgroup:
#     name: netgroup
#     driver: bridge
#     attachable: true
#     ipam:
#       config:
#         - subnet: 172.18.0.0/16
#           gateway: 172.18.0.1