version: '3.8'
services:
  # FastAPI Server
  api:
    hostname: api
    container_name: api
    # image: jungfrau70/api-gateway:0.1
    build: .
    restart: always
    tty: true
    ports:
      - 8000:8000
    # volumes:
    #   - ./api:/usr/src/api
    deploy:
      resources:
        limits:
          memory: 1g          