version: '3.8'
services:
  # Agent in deployment
  data-processor:
    hostname: data-processor
    container_name: data-processor
    # image: jungfrau70/data-processor:0.6
    build: .
    restart: always
    tty: true
    deploy:
      resources:
        limits:
          memory: 1g              