version: '3'
services:
  data-processor:
    hostname: data-processor
    container_name: data-processor
    image: jungfrau70/data-processor:0.6
    restart: always
    deploy:
      resources:
        limits:
          memory: 1g