version: '3'
services:
  db-loader:
    hostname: db-loader
    container_name: db-loader
    image: jungfrau70/db-loader:0.1
    # networks:
    #   netgroup:
    #     ipv4_address: 172.18.0.101
    # environment:
    #   kafka1: 172.17.38.194
    #   kafka2: 172.17.38.194
    #   kafka3: 172.17.38.194
    deploy:
      resources:
        limits:
          memory: 1g
# networks:
#   netgroup:
#     name: netgroup
#     driver: bridge
#     attachable: true
#     ipam:
#       config:
#         - subnet: 172.18.0.0/16
#           gateway: 172.18.0.1