version: '3'
services:
  data-processor:
    hostname: data-processor
    container_name: data-processor
    image: jungfrau70/api-gateway:0.1
    restart: always
    deploy:
      resources:
        limits:
          memory: 1g