version: '3.8'
services:
  # Lens Client :: Node.js
  web:
    hostname: web-websocket
    container_name: web-websocket
    # image: jungfrau70/lens-frontend:0.1
    build: .
    restart: always
    tty: true
    ports:
      - 8080:8080
    env_file:
      - .env      
    deploy:
      resources:
        limits:
          memory: 1g     